services:
    api:
        build:
            context: .
        restart: always
        environment:
            DATABASE_URL: "file:/app/data/prod.db"
            PORT: 3000
        volumes:
            - ./data:/app/data
        ports:
            - "3000:3000"
        command: sh -c "mkdir -p /app/data && npx prisma migrate deploy && node dist/main.js"
        env_file:
            - .env
